version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    environment:
      GO111MODULE: "on"

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Fetch dependencies
          command: go get ./...

      - run:
          name: Run unit tests
          command: go test

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
